# Generated by Django 4.2.1 on 2023-06-02 12:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Veterinaria', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['id'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='historiaclinica',
            options={'ordering': ['id'], 'verbose_name': 'Historia clinica', 'verbose_name_plural': 'Historias clinicas'},
        ),
        migrations.AlterModelOptions(
            name='mascota',
            options={'ordering': ['id'], 'verbose_name': 'Mascota', 'verbose_name_plural': 'Mascotas'},
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fecha_alta',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 6, 2, 9, 19, 41, 288679), max_length=15, verbose_name='Fecha de alta'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='fecha_consulta',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 6, 2, 9, 19, 41, 288679), verbose_name='Fecha de consulta'),
        ),
    ]
