# Generated by Django 4.2.1 on 2023-06-02 12:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Veterinaria', '0002_alter_cliente_options_alter_historiaclinica_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha_alta',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 6, 2, 9, 37, 14, 437597), max_length=15, verbose_name='Fecha de alta'),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='fecha_consulta',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 6, 2, 9, 37, 14, 438602), verbose_name='Fecha de consulta'),
        ),
    ]
