# Generated by Django 4.2.1 on 2023-06-02 16:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Veterinaria', '0004_alter_cliente_fecha_alta_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historiaclinica',
            old_name='mascota_id',
            new_name='mascota',
        ),
        migrations.RenameField(
            model_name='mascota',
            old_name='cliente_id',
            new_name='cliente',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fecha_alta',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 6, 2, 16, 15, 50, 619896, tzinfo=datetime.timezone.utc), verbose_name='Fecha de alta'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='fecha_consulta',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 6, 2, 16, 15, 50, 620898, tzinfo=datetime.timezone.utc), verbose_name='Fecha de consulta'),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
