# Generated by Django 4.2.1 on 2023-06-02 16:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Veterinaria', '0005_rename_mascota_id_historiaclinica_mascota_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha_alta',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 6, 2, 16, 25, 11, 264118, tzinfo=datetime.timezone.utc), verbose_name='Fecha de alta'),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='fecha_consulta',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 6, 2, 16, 25, 11, 265131, tzinfo=datetime.timezone.utc), verbose_name='Fecha de consulta'),
        ),
    ]
