# Generated by Django 4.2.1 on 2023-06-16 20:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Veterinaria', '0013_alter_cliente_fecha_alta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mascota',
            name='cliente',
        ),
        migrations.AddField(
            model_name='cliente',
            name='username',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fecha_alta',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 6, 16, 20, 44, 22, 843279, tzinfo=datetime.timezone.utc), verbose_name='Fecha de alta'),
        ),
        migrations.DeleteModel(
            name='HistoriaClinica',
        ),
        migrations.DeleteModel(
            name='Mascota',
        ),
    ]
