# Generated by Django 4.2.1 on 2023-06-16 20:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Veterinaria', '0014_remove_mascota_cliente_cliente_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha_alta',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 6, 16, 20, 44, 30, 855521, tzinfo=datetime.timezone.utc), verbose_name='Fecha de alta'),
        ),
    ]
