# Generated by Django 4.2.1 on 2023-06-21 05:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Veterinaria', '0015_alter_cliente_fecha_alta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha_alta',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 6, 21, 5, 1, 42, 440106, tzinfo=datetime.timezone.utc), verbose_name='Fecha de alta'),
        ),
    ]
